env: "local" # local, dev, prod
log_level: "DEBUG" # DEBUG, INFO, WARN, ERROR

server:
  host: "localhost"
  port: 8082
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1221"
  db: "hotel"
  sslmode: "disable"
