services:
  postgres:
    image: "imresamu/postgis:17-3.6"
    container_name: "postgres"
    volumes:
      - pg_data:/data
    environment:
      PGDATA: "/data"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
