basePath: /api/v1
definitions:
  request.UserActiveStatus:
    properties:
      is_active:
        type: boolean
    required:
    - is_active
    type: object
  request.UserCreate:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: strongpass123!#
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  request.UserRoleStatus:
    properties:
      role:
        example: user
        type: string
    required:
    - role
    type: object
  request.UserUpdate:
    properties:
      email:
        example: user@example.com
        type: string
      username:
        example: username
        type: string
    type: object
  response.ErrorSchema:
    properties:
      message:
        type: string
      type:
        type: string
    type: object
  response.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      token_type:
        example: Bearer
        type: string
    type: object
  response.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  response.UserActiveStatus:
    properties:
      is_active:
        type: boolean
      message:
        type: string
    type: object
  response.UserList:
    properties:
      current_page:
        type: integer
      limit:
        type: integer
      links:
        $ref: '#/definitions/response.UserListLinks'
      total_page_count:
        type: integer
      total_users_count:
        type: integer
      users:
        items:
          $ref: '#/definitions/response.UserShort'
        type: array
    type: object
  response.UserListLinks:
    properties:
      first:
        type: string
      last:
        type: string
      next:
        type: string
      prev:
        type: string
    type: object
  response.UserRoleStatus:
    properties:
      message:
        type: string
      role:
        type: string
    type: object
  response.UserShort:
    properties:
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Auth service for microservices.
  title: Swagger Auth API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user by email and return access and refresh tokens
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Token'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      summary: Login user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh access tokenCreds and return new tokenCreds data
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          properties:
            refresh_token:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Token'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      summary: Refresh access user tokenCreds
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user by email and return access and refresh tokens
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      summary: Register user
      tags:
      - auth
  /users/:
    get:
      consumes:
      - application/json
      description: Get users from admin or moderator provider
      parameters:
      - default: 1
        description: Page
        in: query
        name: page
        type: integer
      - default: 100
        description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserList'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user account from admin provider
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Create user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user by ID from admin or owner provider
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Delete user by ID
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user by ID from admin, moderator or owner provider
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Get user by ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user by ID from admin or owner provider
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Update user by ID
      tags:
      - users
  /users/{id}/role:
    put:
      consumes:
      - application/json
      description: Update user by ID from admin or owner provider
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserRoleStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserRoleStatus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Update user by ID
      tags:
      - users
  /users/{id}/status:
    put:
      consumes:
      - application/json
      description: Update user by ID from admin or owner provider
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserActiveStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserActiveStatus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorSchema'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorSchema'
      security:
      - Bearer: []
      summary: Update user by ID
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
